import React, { useState } from 'react';

const ReportView = ({ data }) => {
    const [copied, setCopied] = useState(false);
    const [downloading, setDownloading] = useState(false);
    const [activeSection, setActiveSection] = useState(null);

    const summary = data?.summary || {};
    const report = data?.report || '';

    if (!report) {
        return (
            <div className="p-10 text-center text-gray-400 italic">
                Generating final report...
            </div>
        );
    }

    const handleCopy = () => {
        navigator.clipboard.writeText(report).then(() => {
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        });
    };

    // ----------------------------------------------------------------
    // PDF DOWNLOAD — uses a hidden popup window + browser print-to-PDF
    // No external library required.
    // ----------------------------------------------------------------
    const handleDownloadPDF = () => {
        setDownloading(true);

        // Build styled HTML for the print window
        const timestamp = new Date().toLocaleDateString('en-GB', {
            day: '2-digit', month: 'long', year: 'numeric'
        });

        const lines = report.split('\n');
        const htmlBody = lines.map(line => {
            const trimmed = line.trim();
            if (!trimmed) return '<br/>';
            // All-caps lines = section headings
            if (/^[A-Z\s&]{4,}$/.test(trimmed) && trimmed.length > 0) {
                return `<h2>${trimmed}</h2>`;
            }
            // Separator lines
            if (/^[-=]{3,}/.test(trimmed)) return '<hr/>';
            return `<p>${trimmed}</p>`;
        }).join('\n');

        const printHtml = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>LitScout — Literature Review Report</title>
  <style>
    @page {
      size: A4;
      margin: 25mm 20mm 25mm 20mm;
    }
    * { box-sizing: border-box; }
    body {
      font-family: 'Georgia', serif;
      font-size: 11pt;
      color: #1a1a2e;
      line-height: 1.75;
      padding: 0;
      margin: 0;
    }
    /* Cover header */
    .cover {
      text-align: center;
      margin-bottom: 32pt;
      padding-bottom: 16pt;
      border-bottom: 2px solid #4f46e5;
    }
    .cover h1 {
      font-size: 20pt;
      font-weight: 900;
      color: #4f46e5;
      margin: 0 0 6pt;
      letter-spacing: 0.5pt;
    }
    .cover .subtitle {
      font-size: 10pt;
      color: #6b7280;
      font-style: italic;
    }
    .cover .meta {
      font-size: 9pt;
      color: #9ca3af;
      margin-top: 8pt;
    }
    /* Stats bar */
    .stats {
      display: flex;
      gap: 12pt;
      margin-bottom: 20pt;
      justify-content: center;
    }
    .stat-box {
      border: 1px solid #e5e7eb;
      border-radius: 6pt;
      padding: 6pt 12pt;
      text-align: center;
    }
    .stat-label {
      font-size: 7pt;
      text-transform: uppercase;
      letter-spacing: 1pt;
      color: #9ca3af;
      font-weight: 700;
    }
    .stat-value {
      font-size: 14pt;
      font-weight: 900;
      color: #4f46e5;
    }
    /* Section headings */
    h2 {
      font-size: 12pt;
      font-weight: 800;
      color: #4f46e5;
      text-transform: uppercase;
      letter-spacing: 1.5pt;
      margin: 20pt 0 4pt;
      padding-bottom: 3pt;
      border-bottom: 1px solid #e0e7ff;
    }
    p {
      margin: 5pt 0;
      text-align: justify;
    }
    hr {
      border: none;
      border-top: 1px solid #e5e7eb;
      margin: 10pt 0;
    }
    /* Page break before each major section */
    h2 { page-break-before: auto; }
    /* Footer */
    @media print {
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="cover">
    <h1>Literature Review Report</h1>
    <div class="subtitle">Generated by LitScout &mdash; Multi-Agent AI Research System</div>
    <div class="meta">Generated on ${timestamp}</div>
  </div>

  <div class="stats">
    <div class="stat-box">
      <div class="stat-label">Words</div>
      <div class="stat-value">${summary.word_count ?? report.split(' ').length}</div>
    </div>
    <div class="stat-box">
      <div class="stat-label">Sections</div>
      <div class="stat-value">${summary.section_count ?? '—'}</div>
    </div>
    <div class="stat-box">
      <div class="stat-label">Themes</div>
      <div class="stat-value">${summary.theme_count ?? '—'}</div>
    </div>
    <div class="stat-box">
      <div class="stat-label">QA Score</div>
      <div class="stat-value">${summary.quality_score !== undefined && summary.quality_score !== 'N/A'
                ? Number(summary.quality_score).toFixed(1) + '/10'
                : '—'
            }</div>
    </div>
  </div>

  ${htmlBody}
</body>
</html>`;

        // Open print popup
        const printWindow = window.open('', '_blank', 'width=900,height=700');
        if (!printWindow) {
            alert('Pop-up blocked! Please allow pop-ups for this site and try again.');
            setDownloading(false);
            return;
        }

        printWindow.document.write(printHtml);
        printWindow.document.close();

        // Trigger print dialog after content renders
        printWindow.onload = () => {
            setTimeout(() => {
                printWindow.focus();
                printWindow.print();
                // Close popup after user dismisses print dialog
                printWindow.onafterprint = () => printWindow.close();
                setDownloading(false);
            }, 400);
        };
    };

    // Parse sections from the formatted report
    const parseSections = (text) => {
        const lines = text.split('\n');
        const sections = [];
        let current = null;

        for (const line of lines) {
            if (/^[A-Z\s&]{4,}$/.test(line.trim()) && line.trim().length > 0) {
                if (current) sections.push(current);
                current = { title: line.trim(), content: [] };
            } else if (line.startsWith('---') || line.startsWith('===')) {
                // separator — skip
            } else if (current) {
                current.content.push(line);
            }
        }
        if (current) sections.push(current);
        if (sections.length === 0) {
            return [{ title: 'Full Report', content: text.split('\n') }];
        }
        return sections;
    };

    const sections = parseSections(report);

    return (
        <div className="space-y-5 animate-fadeIn">

            {/* Stats Row */}
            <div className="grid grid-cols-4 gap-3">
                <div className="bg-indigo-50 p-3 rounded-xl border border-indigo-100 text-center">
                    <p className="text-[10px] font-bold text-indigo-500 uppercase tracking-wider">Words</p>
                    <p className="text-2xl font-black text-indigo-700">{summary.word_count ?? report.split(' ').length}</p>
                </div>
                <div className="bg-blue-50 p-3 rounded-xl border border-blue-100 text-center">
                    <p className="text-[10px] font-bold text-blue-500 uppercase tracking-wider">Sections</p>
                    <p className="text-2xl font-black text-blue-700">{summary.section_count ?? sections.length}</p>
                </div>
                <div className="bg-purple-50 p-3 rounded-xl border border-purple-100 text-center">
                    <p className="text-[10px] font-bold text-purple-500 uppercase tracking-wider">Themes</p>
                    <p className="text-2xl font-black text-purple-700">{summary.theme_count ?? '—'}</p>
                </div>
                <div className="bg-emerald-50 p-3 rounded-xl border border-emerald-100 text-center">
                    <p className="text-[10px] font-bold text-emerald-500 uppercase tracking-wider">QA Score</p>
                    <p className="text-2xl font-black text-emerald-700">
                        {summary.quality_score !== undefined && summary.quality_score !== 'N/A'
                            ? Number(summary.quality_score).toFixed(1)
                            : '—'}
                    </p>
                </div>
            </div>

            {/* Method + Status + Download Button */}
            <div className="flex items-center justify-between gap-2 flex-wrap">
                <div className="flex gap-2 flex-wrap">
                    <span className="text-[10px] bg-slate-100 text-slate-500 px-2 py-1 rounded-full font-bold uppercase tracking-wider">
                        {summary.method || 'LangGraph report generation'}
                    </span>
                    <span className={`text-[10px] px-2 py-1 rounded-full font-bold uppercase tracking-wider ${summary.status === 'complete'
                            ? 'bg-green-100 text-green-600'
                            : 'bg-amber-100 text-amber-600'
                        }`}>
                        {summary.status ?? 'complete'}
                    </span>
                </div>

                {/* PDF Download Button */}
                <button
                    onClick={handleDownloadPDF}
                    disabled={downloading}
                    className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-bold transition-all shadow-sm ${downloading
                            ? 'bg-gray-100 text-gray-400 cursor-not-allowed'
                            : 'bg-indigo-600 text-white hover:bg-indigo-700 active:scale-95'
                        }`}
                >
                    {downloading ? (
                        <><span className="animate-spin">⟳</span> Preparing...</>
                    ) : (
                        <><span>↓</span> Download PDF</>
                    )}
                </button>
            </div>

            {/* Section Navigator */}
            {sections.length > 1 && (
                <div className="flex gap-2 flex-wrap">
                    <button
                        onClick={() => setActiveSection(null)}
                        className={`text-[10px] px-3 py-1 rounded-full font-bold transition-colors ${activeSection === null
                                ? 'bg-indigo-500 text-white'
                                : 'bg-gray-100 text-gray-500 hover:bg-gray-200'
                            }`}
                    >
                        All
                    </button>
                    {sections.map((s, i) => (
                        <button
                            key={i}
                            onClick={() => setActiveSection(i)}
                            className={`text-[10px] px-3 py-1 rounded-full font-bold capitalize transition-colors ${activeSection === i
                                    ? 'bg-indigo-500 text-white'
                                    : 'bg-gray-100 text-gray-500 hover:bg-gray-200'
                                }`}
                        >
                            {s.title.length > 20 ? s.title.slice(0, 20) + '…' : s.title}
                        </button>
                    ))}
                </div>
            )}

            {/* Report Content */}
            <div className="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden">
                <div className="flex justify-between items-center px-5 py-3 bg-gray-50 border-b border-gray-100">
                    <span className="text-xs font-bold text-gray-500 uppercase tracking-widest flex items-center gap-2">
                        <span className="text-indigo-500">▣</span>
                        {activeSection !== null ? sections[activeSection]?.title : 'Full Report'}
                    </span>
                    <button
                        onClick={handleCopy}
                        className="text-[11px] text-gray-400 hover:text-indigo-600 transition-colors font-medium flex items-center gap-1"
                    >
                        {copied ? '✓ Copied!' : '⎘ Copy'}
                    </button>
                </div>

                <div className="p-6 text-sm text-slate-700 leading-relaxed font-serif max-h-[350px] overflow-y-auto custom-scrollbar space-y-4">
                    {activeSection !== null ? (
                        sections[activeSection]?.content
                            .filter(l => l.trim().length > 0)
                            .map((line, i) => <p key={i}>{line}</p>)
                    ) : (
                        sections.map((sec, si) => (
                            <div key={si} className="space-y-2">
                                {sections.length > 1 && (
                                    <h4 className="text-xs font-black uppercase tracking-widest text-indigo-600 mt-4 mb-1">
                                        {sec.title}
                                    </h4>
                                )}
                                {sec.content
                                    .filter(l => l.trim().length > 0)
                                    .map((line, li) => (
                                        <p key={li} className={li === 0 ? 'text-slate-800 font-medium' : 'text-slate-700'}>
                                            {line}
                                        </p>
                                    ))}
                            </div>
                        ))
                    )}
                </div>
            </div>

        </div>
    );
};

export default ReportView;
